language: csharp
solution: CardSharp.sln
install:
- sudo apt-get install -y gtk-sharp2
- nuget restore CardSharp.sln
script:
- xbuild /p:Configuration=Release CardSharp.sln
- "./pack.sh"
deploy:
  provider: releases
  api_key:
    secure: cgXtFsR8W2V84Q+aVcoHyb91V7vw2Jm4lgH4R4BTO5yIEJodlh5sbjJii3xycblrbkC1LUXzylzNZ/QhFIBqAjIB806AXfdHCnPrc/ZaWwaLDz7/NwAhgcY7mbX8e3dBv9stLvPjCFvyM9ovtpa2lbhqGENWPfwoafkyZVszEAknFXnAJZg5jgFLk7UDhY2I8GerapfCoAlyMCtPfgEYOkazav7jU4Wlc1l+8t0s98Zg8tgn6C+d6ZYRSq8kXHZBcE1d6BgqBGT7eC1e1Dr7kDXY9YNyFwAulkK3oPA/yJjMYJ5BQD1uubGZVVfdQAapeWAoRF6y+YMwJudJI2OFo3k90zbHYda6/xCLrXFtNcgGDE7e2m9Cqfy1DbtMlSQun0zv7m1G+AfBPMUzFZN6OfZUmFwTxuThSzHwhHcOgh3kSxkHSa3WMEXdjhMO5iLTLmt4h42Q48y7cbkgCidHwxyx/eZy4EeY1ndikH85HhxQq47pIeLJn5Ztbtxb/clY6SfJPJPP24vNzhEDTKtxJFTEoCz+iUCF8/u9+W0RO2LxI6YjFJ50enAiYrf5lmKXg7g2PasC5v7rUXltulv36U/u4jlhsdqTVR4Bq0Gi6iBdikrEq3p6uv4IJUtoG9kbl1WlpFQ97SgBNvAlmPFgSGdov7aMsLVCBoMrOH8iCa8=
  file:
    - "CardSharp/bin/Release/CardSharp.dll"
    - "Origind.Card.Game/bin/CQP-All.zip"
  on:
    repo: Cyl18/CardSharp
  skip_cleanup: true
